# Generated by Django 4.2.7 on 2024-02-23 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "contactid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("employees", models.CharField(max_length=100)),
                ("reoson", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "feedbackid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("service", models.CharField(max_length=11)),
                ("rating", models.IntegerField()),
                ("comment", models.CharField(max_length=50)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
