# Generated by Django 4.2.7 on 2024-02-23 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticketid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("request", models.CharField(blank=True, max_length=100)),
                ("opendate", models.DateTimeField(auto_now_add=True)),
                ("closingdate", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pa.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointmentid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pa.task"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="da.ticket"
                    ),
                ),
            ],
        ),
    ]
