# Generated by Django 5.0.4 on 2024-04-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0001_initial'),
        ('pa', '0002_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pa.task'),
        ),
    ]
