# Generated by Django 5.0.4 on 2024-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='pop',
            field=models.ImageField(upload_to='static/pops'),
        ),
    ]
