# Generated by Django 5.0.4 on 2024-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0005_ecocashwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecocashwithdrawal',
            name='currency',
            field=models.CharField(default='ZiG', max_length=50),
        ),
    ]
