# Generated by Django 5.0.4 on 2024-04-12 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0006_ecocashwithdrawal_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipitWithdrawal',
            fields=[
                ('zipitwithdrawalid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=50)),
                ('currency', models.CharField(default='ZiG', max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
                ('financialinstitution', models.CharField(default='', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
