# Generated by Django 5.0.4 on 2024-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0007_zipitwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipitwithdrawal',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
