# Generated by Django 5.0.4 on 2024-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0008_zipitwithdrawal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipitwithdrawal',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='dates'),
        ),
    ]
