# Generated by Django 5.0.4 on 2024-04-15 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('websiteid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usersss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('webpageid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userss', to=settings.AUTH_USER_MODEL)),
                ('webpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websitess', to='sa.website')),
            ],
        ),
    ]
