# Generated by Django 5.0.4 on 2024-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='webpage',
            field=models.ImageField(blank=True, default='', upload_to='static/webpages'),
        ),
    ]
