# Generated by Django 5.0.4 on 2024-04-17 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('prmocodeid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('code', models.IntegerField()),
                ('opendate', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
