# Generated by Django 5.0.4 on 2024-04-18 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_rename_prmocodeid_promocode_promocodeid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('activationid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('payout', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
