# Generated by Django 5.0.4 on 2024-04-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0004_activation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rankid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('recruit', models.IntegerField()),
                ('branchsize', models.IntegerField()),
                ('responsibility', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Myaccount',
            fields=[
                ('myaccountid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('recruitedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daterecruited', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.rank')),
            ],
        ),
    ]
