# Generated by Django 5.0.4 on 2024-04-20 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_rank_myaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('invitationid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('opendate', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
