# Generated by Django 5.0.4 on 2024-04-21 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_invitationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportto',
            fields=[
                ('reporttoid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporttoaccount', to=settings.AUTH_USER_MODEL)),
                ('reportto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
