# Generated by Django 4.2.7 on 2024-02-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
